### ISSUE TITLE
user-can-turn-their-car

### ISSUE THREAD

**Issue by tychiang922** [tychiang922/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create js transform variables to rotate objects 90 degrees and -90 degrees
- [x] Add keypress event listeners for arrow keys
- [x] Add animate() and finish() methods to the car img when certain arrow keys are fired
- [x] Consider recording the current direction the car is facing into a separate variable for later use
