### ISSUE TITLE
user-can-start-their-car

### ISSUE THREAD

**Issue by tychiang922** [tychiang922/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Create a data model that will hold all current positioning of the car
- [x] Create a function that will move the car based on top and left positioning
- [x] Create a interval that will run the function every 16ms
- [x] Create an event listener to the space keyup to activate the interval
