### ISSUE TITLE
user-can-stop-their-car

### ISSUE THREAD

**Issue by tychiang922** [tychiang922/driving-game#7]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] In the same event listener as startCar, listen for space key press and check whether car is currently running
- [x] If car is running, stop the interval from running once space key is press
- [x] Record the car stopping in the car data object
